version: "3"
services:

  frontend:
    image: frontend
    build: .
    ports:
    - 8080:8080
    environment:
        BACKEND_DNS: backend
        BACKEND_PORT: 9000

  backend:
    container_name: backend-container
    image: backend
    build: .
    ports:
    - 9000:9000