apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
  labels:
    name: pvc-redis
    app: redis-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
