apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-databaseservice
  name: test-databaseservice
spec:
  ports:
  - port: 6380  
    protocol: TCP
    targetPort: 6379
  selector:
    app: test-databasedeployment
  type: ClusterIP
