apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-backenddeployment
  name: test-backenddeployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: test-backenddeployment
  template:
    metadata:
      labels:
        app: test-backenddeployment
    spec:
      containers:
      - name: test-backenddeployment
        image: olexmeister/backend-dev:c4d4a0b86918ab669639b98da3819c1f0c31499f
        env:
          - name: REDIS_DNS
            value: test-databaseservice
