apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-backendservice
  name: test-backendservice
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9000
  selector:
    app: test-backenddeployment
  type: ClusterIP
