apiVersion: v1
kind: Service
metadata:
  name: test-frontendservice
  labels:
    app: test-frontendservice
spec:
  selector:
    app: test-frontenddeployment
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
