apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-frontenddeployment
  labels:
    app: test-frontenddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-frontenddeployment
  template:
    metadata:
      labels:
        app: test-frontenddeployment
    spec:
      containers:
      - name: test-frontenddeployment
        image: olexmeister/frontend-dev:c4d4a0b86918ab669639b98da3819c1f0c31499f
        env:
          - name: BACKEND_DNS
            value: test-backendservice
          - name: BACKEND_PORT
            value: "9000"