apiVersion: v1
kind: Service
metadata:
  labels:
    app: databaseservice
  name: databaseservice
spec:
  ports:
  - port: 6379  
    protocol: TCP
    targetPort: 6379
  selector:
    app: databasedeployment
  type: ClusterIP
