apiVersion: v1
kind: Service
metadata:
  labels:
    app: backenddeployment
  name: backendservice
spec:
  selector:
    app: backenddeployment
  type: ClusterIP
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
