apiVersion: apps/v1
kind: Deployment
metadata:
  name: databasedeployment
  labels:
    app: databasedeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: databasedeployment
  template:
    metadata:
      labels:
        app: databasedeployment
    spec:
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redisvolumeclaim1
      containers:
      - name: redis
        image: redis:alpine
        volumeMounts:
          - mountPath: "/data"
            name: redis-volume
