apiVersion: v1
kind: Service
metadata:
  labels:
    app: databaseservice
  name: databaseservice
spec:
  selector:
    app: databasedeployment
  type: ClusterIP
  ports:
  - port: 6379  
    targetPort: 6379
    protocol: TCP
