apiVersion: v1
kind: Service
metadata:
  name: frontendservice
  labels:
    app: frontendservice
spec:
  selector:
    app: frontenddeployment
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
