apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontenddeployment
  labels:
    app: frontenddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontenddeployment
  template:
    metadata:
      labels:
        app: frontenddeployment
    spec:
      containers:
      - name: frontenddeployment
        image: olexmeister/frontend:137850ff42f8fbef4c39d31cb5e4df0bc16a0d7b
        env:
          - name: BACKEND_DNS
            value: backendservice
          - name: BACKEND_PORT
            value: "9000"