apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontenddeployment
  labels:
    app: frontenddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontenddeployment
  template:
    metadata:
      labels:
        app: frontenddeployment
    spec:
      containers:
      - name: frontenddeployment
        image: olexmeister/frontend:d20c8d560d7f5ac5172e1a3000c7d29e5e3bd872
        env:
          - name: BACKEND_DNS
            value: backendservice
          - name: BACKEND_PORT
            value: "9000"