apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisvolumeclaim1
  labels:
    name: redisvolumeclaim1
    app: redis-volume
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
