name: Go webpage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Clone:
    name: Clone repo
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Upload repo for other jobs
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Test:
    name: Test script
    runs-on: ubuntu-latest
    needs: Clone
    steps:
      - name: Download repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Run frontend test
        run: chmod +x ci/test.sh && ci/test.sh